#!/bin/bash

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1,16,31,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        mkdir -p yesterday
        mkdir -p today
        mkdir -p nextday
        for country in AT BE CH DE DK1 DK2 FI FR NL NO1 NO2 NO3 NO4 NO5 PL SE1 SE2 SE3 SE4 
        do
          export output_file=$(echo "${country}.html" | awk '{print tolower($0)}')
          yesterday=$(date --date="yesterday" +"%Y-%m-%d")
          today=$(date --date="today" +"%Y-%m-%d")
          nextday=$(date --date="next day" +"%Y-%m-%d")
          curl "https://www.epexspot.com/en/market-data?delivery_date=${yesterday}&market_area=${country}&trading_date=&underlying_year=&modality=Continuous&sub_modality=&product=60&data_mode=table&period=" > "yesterday/${output_file}"
          curl "https://www.epexspot.com/en/market-data?delivery_date=${today}&market_area=${country}&trading_date=&underlying_year=&modality=Continuous&sub_modality=&product=60&data_mode=table&period=" > "today/${output_file}"
          curl "https://www.epexspot.com/en/market-data?delivery_date=${nextday}&market_area=${country}&trading_date=&underlying_year=&modality=Continuous&sub_modality=&product=60&data_mode=table&period=" > "nextday/${output_file}"
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u --rfc-3339=seconds)
        git commit -m "Latest data (UTC): ${timestamp}" || exit 0
        git push
